[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["!node_modules/@next/swc-*/**/*"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 現在のNode.jsバージョンを確認
node -v

# Node.js v18をインストール（管理者権限のコマンドプロンプトで実行）
nvm install 18.19.0
nvm use 18.19.0